version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image:  node:alpine
      - image: selenium/standalone-chrome:3.1.0
        environment:
          CHROME_BIN: "/usr/bin/google-chrome"
    steps:
      - checkout
      - run: 
          name: Cleaning npm cache
          command: npm cache clean --force
      - run: 
          name : Install cordova
          command : npm i -g cordova
      - run: 
          name : see work dir
          command : ls -la
      - run: 
          name: Rebuild node-sass to avoid install problems
          command: npm rebuild node-sass --force  
      - run:
          name : Install ionic
          command : npm i -g ionic
      - run:
          name: Install node modules
          command: npm install
      - run:
          name: Run unit tests
          command: npm test
      - run:
          name: Building android
          command: ionic cordova build android
      - store_artifacts:
          path: platforms/android/build/outputs/apk/android-debug.apk